### ISSUE TITLE
Refatoração completa e compatibilidade com GiveWP 3.0.0

### ISSUE THREAD

**Issue by emanuellopess** [LinkNacional/give-multimoeda#18]
- [x] Adicionar compatibilidade com formulário 3.0.0;
- [x] Adicionar compatibilidade com templates legado;
- [x] Refatorar código e simplificar;
- [x] Passar em todos os testes do [Plugin Checker](https://wordpress.org/plugins/plugin-check/);
- [x] Plugin deve seguir as [normativas de desenvolvimento](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/) do WordPress

**Comment by Abraao2005** [comment]
![image](https://github.com/user-attachments/assets/74a185b7-df18-4f4f-ae5e-2bd9690d255a)
Apenas esses "erros" aparecendo no plugin checker
